# NumPy Arrays

In [1]:
list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_list = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,3/2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.linspace(0,9,10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.random.rand(5)

array([0.78205395, 0.2263657 , 0.15995913, 0.61014217, 0.13388876])

In [26]:
np.random.rand(5,5)

array([[0.7643307 , 0.69441341, 0.41401978, 0.67245022, 0.88164197],
       [0.57490397, 0.62678158, 0.30849259, 0.38959536, 0.0254922 ],
       [0.13686762, 0.05604197, 0.0142384 , 0.72684183, 0.48369116],
       [0.09859019, 0.92029613, 0.80532106, 0.0140495 , 0.16345894],
       [0.07277813, 0.63012712, 0.85966971, 0.04559377, 0.05435504]])

In [34]:
np.random.randn(4,4)

array([[ 0.41166545, -0.23315363,  0.03616067, -0.16992483],
       [-1.4676856 , -0.2535428 ,  0.1077091 , -1.19206775],
       [-0.89021651,  0.1269958 , -0.125642  ,  0.25131181],
       [-2.4740507 ,  0.14728327,  0.29166502, -0.12994968]])

In [41]:
np.random.randint(1,100)

17

In [42]:
arr = np.arange(25)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [46]:
ranarr = np.random.randint(0,50,10)

In [47]:
ranarr

array([10, 46, 30, 42, 11, 36,  9, 21, 42, 27])

In [51]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
ranarr

array([10, 46, 30, 42, 11, 36,  9, 21, 42, 27])

In [54]:
ranarr.max()

46

In [55]:
ranarr.min()

9

In [56]:
ranarr.argmax()

1

In [57]:
ranarr.argmin()

6

In [59]:
arr.shape

(25,)

In [60]:
arr = arr.reshape(5,5)

In [61]:
arr.shape

(5, 5)

In [64]:
arr.dtype

dtype('int32')

In [67]:
from numpy.random import randint

In [68]:
randint(2,10)

8